### ISSUE TITLE
Error when doing Hocon.load where there is a substitution  

### ISSUE THREAD

**Issue by jmccure** [puppetlabs/ruby-hocon#10]
Config file example:
a.b {
  c = ${x.y.z}
}

x {
  y.z = 10 seconds
}

Error:
undefined local variable or method `pull_substitution' for #<Hocon::Impl::Tokenizer::TokenIterator:0x007fe821fb7708> (NameError)
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/tokenizer.rb:309:in `pull_next_token'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/tokenizer.rb:342:in `queue_next_token'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/tokenizer.rb:354:in `next'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parser.rb:842:in `pop_token'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parser.rb:698:in `next_token'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parser.rb:770:in `check_element_separator'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parser.rb:536:in `parse_object'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parser.rb:341:in `parse_value'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parser.rb:477:in `parse_object'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parser.rb:654:in `parse'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parser.rb:880:in `parse'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parseable.rb:186:in `raw_parse_value_from_io'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parseable.rb:180:in `block in raw_parse_value'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parseable.rb:34:in `block in open'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parseable.rb:33:in `open'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parseable.rb:33:in `open'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parseable.rb:179:in `raw_parse_value'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parseable.rb:163:in `parse_value_from_origin'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parseable.rb:116:in `parse_value'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/impl/parseable.rb:99:in `parse'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon/config_factory.rb:7:in `parse_file'
/Users/jaym/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/hocon-0.0.4/lib/hocon.rb:5:in `load'

**Comment by KevinCorcoran** [comment]
@fpringvaldsen Is this issue covered by any of our JIRA tickets?  Or maybe even fixed already?

**Comment by fpringvaldsen** [comment]
@KevinCorcoran I don't think it's fixed yet, but it should be fixed by [TK-161](https://tickets.puppetlabs.com/browse/TK-161)

**Comment by fpringvaldsen** [comment]
Substitution has been working for a while and we have a large amount of test coverage around it, so I'm going to close out this issue.

**Comment by faizhasim** [comment]
@fpringvaldsen, question: Is this really fixed?

I was doing something similar:

```
a: "yes"
b: ${a}
```

and got: `need to Config#resolve, see the API docs for Config#resolve; substitution not resolved: ConfigReference(${a})`

Additionally, I want to substitute value from system environment, like this:

```
server.port: 8080
server.port: ${?PORT}
```

but I got this error: `called unwrapped() on value with unresolved substitutions, need to Config#resolve() first, see API docs`.

**Comment by fpringvaldsen** [comment]
@faizhasim Does it work for you if you load the file with `Hocon::ConfigFactory.load_file`? I think you might be running into https://github.com/puppetlabs/ruby-hocon/issues/67
