### ISSUE TITLE
How to print HOCON style string?

### ISSUE THREAD

**Issue by aibou** [puppetlabs/ruby-hocon#69]
I tried to convert to HOCON style string from JSON, but I could not.
I thought that use it such as:

```ruby
json = <<-EOS
{
  \"hoge\": \"fuga\"
}
EOS

Hocon.parse(json).to_hocon
#=> "\"hoge\" = \"fuga\""
```

Can you tell me how to do it?

**Comment by fpringvaldsen** [comment]
@aibou `Hocon.parse()` parses a HOCON-compatible string and returns a hash. 

If you want to get a HOCON style string, you can either use `Hocon.load()` to load a JSON file, and then call `.root.render` on the resulting object, or you can use `Hocon::ConfigFactory.parse_string` to parse a JSON string. This will give you something similar to `Hocon.load()`, except it won't resolve substitutions, so you can call `.root.render` on that object as well.

You can pass the `render` method an instance of `Hocon::ConfigRenderOptions` if you want to control the format of the output.

**Comment by cprice404** [comment]
@aibou Hopefully that does what you need?  Closing this out but feel free to re-open it if you still have an issue.

**Comment by patcable** [comment]
This was one of the only google hits i got as I was trying to figure out how to take a ruby hash and output it to a hocon-flavored config. The advice above was helpful to get started; but took me a way longer than I was anticipating to figure out exactly how to do it. Hopefully this helps someone else in the future 🙂

```
require 'hocon/config_factory'
require 'json'
render_opts = Hocon::ConfigRenderOptions.new(false, false, true, false)
cool_hash = {'config': { 'option' => 'value' }}
puts Hocon::ConfigFactory.parse_string(cool_hash.to_json).root.render(render_opts)
```
